//HintName: GeNet.Equals.GenerateEqualsAttribute.g.cs
//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/GregDomzalski/GeNet
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace GeNet
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
    public class GenerateEqualsAttribute : System.Attribute
    {
        [System.Runtime.CompilerServices.CompilerGenerated]
        public GenerateEqualsAttribute()
        {
        }
    }
}