//HintName: Base.Equals.g.cs
//-----------------------------------------------------------------------------
/// <auto-generated>
///     This code was generated by https://github.com/GregDomzalski/GeNet
///
///     Changes to this file may cause incorrect behavior and will be lost if the code
///     is regenerated.
/// </auto-generated>
//-----------------------------------------------------------------------------

#nullable enable

public partial class Base : IEquatable<Base>
{
    public override bool Equals(object? obj)
    {
        if (obj is Base other)
        {
            return Base.Equals(this, other);
        }

        return base.Equals(obj);
    }

    public bool Equals(Base? obj)
    {
        if (obj is null) return false;
        return _field1 == obj._field1;
    }

    public override int GetHashCode()
    {
        HashCode hashCode = new HashCode();
        hashCode.Add(_field1);
        return hashCode.GetHashCode();
    }

    public static bool operator ==(Base left, Base right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Base left, Base right)
    {
        return !(left == right);
    }

}

