//HintName: Derived.Equals.g.cs
//-----------------------------------------------------------------------------
/// <auto-generated>
///     This code was generated by https://github.com/GregDomzalski/GeNet
///
///     Changes to this file may cause incorrect behavior and will be lost if the code
///     is regenerated.
/// </auto-generated>
//-----------------------------------------------------------------------------

#nullable enable

public partial class Derived : IEquatable<Derived>
{
    public override bool Equals(object? obj)
    {
        if (obj is Derived other)
        {
            return Derived.Equals(this, other);
        }

        return base.Equals(obj);
    }

    public bool Equals(Derived? obj)
    {
        if (obj is null) return false;
        return _field2 == obj._field2;
    }

    public override int GetHashCode()
    {
        HashCode hashCode = new HashCode();
        hashCode.Add(_field2);
        return hashCode.GetHashCode();
    }

    public static bool operator ==(Derived left, Derived right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Derived left, Derived right)
    {
        return !(left == right);
    }

}

