namespace GeNet.Common;

public static class Header
{
    public const string Value = @"//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/GregDomzalski/GeNet
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>";
}
