//HintName: TestStruct.Equals.g.cs
//-----------------------------------------------------------------------------
/// <auto-generated>
///     This code was generated by https://github.com/GregDomzalski/GeNet
///
///     Changes to this file may cause incorrect behavior and will be lost if the code
///     is regenerated.
/// </auto-generated>
//-----------------------------------------------------------------------------

#nullable enable

public partial struct TestStruct : IEquatable<TestStruct>
{
    public override bool Equals(object? obj)
    {
        if (obj is TestStruct other)
        {
            return TestStruct.Equals(this, other);
        }

        return base.Equals(obj);
    }

    public bool Equals(TestStruct? obj)
    {
        if (obj is null) return false;
        return _field1 == obj._field1;
    }

    public override int GetHashCode()
    {
        HashCode hashCode = new HashCode();
        hashCode.Add(_field1);
        return hashCode.GetHashCode();
    }

    public static bool operator ==(TestStruct left, TestStruct right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(TestStruct left, TestStruct right)
    {
        return !(left == right);
    }

}

